// src/components/Main.vue
<template>
    <div>
    <div id="head_section">
        <BattleHeader />
        <Auth /> 
    </div>
    <div id="main_section">
        <div id="battlemap"> <BattleMap /></div>
        <div id="rightcolumn">
            <UiTabs>
                <UiTab title="ships">
                    <ListObjects />
                </UiTab>
                <UiTab title="command">
                    <CommandPanel />
                </UiTab>
                <UiTab title="logs">
                    <div>TODO</div>
                </UiTab>
            </UiTabs>
        </div>
    </div>
    </div>
</template>

<script>
import 'keen-ui/dist/keen-ui.css';

import Auth from './Auth/index.vue';
import BattleHeader from './BattleHeader.vue';
import BattleMap from './BattleMap/index.vue';
import ListObjects from './ListObjects.vue';
import CommandPanel from './CommandPanel/index.vue';

import { UiTabs, UiTab } from 'keen-ui';

export default {
    components: { Auth, BattleHeader, BattleMap, ListObjects, UiTabs, UiTab,
        CommandPanel },
};

</script>

// src/components/Main.jsx
import React from 'react';
import HeadSection from './HeadSection';

import BattleMap from './BattleMap';
import ListObjects from './ListObjects';
import CommandPanel from './CommandPanel';
import TurnLog from './TurnLog';

import { Tab, Tabs } from "@blueprintjs/core";
 

import './Main/style.css';

export default () => <div>
    <HeadSection />
    <div id="main_section">
        <div id="battlemap"> <BattleMap /></div>
        <div id="rightcolumn">
            <Tabs renderActiveTabPanelOnly={true}>
                <Tab id="controls" title="command" panel={ <CommandPanel /> } />
                <Tab id="ships" title="ships" panel={ <ListObjects /> } />
                <Tab id="turn_log" title="logs" panel={ <TurnLog /> } />
            </Tabs>
        </div>
    </div>
</div>;
